# Generated by Django 4.2.6 on 2023-12-15 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0009_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
